### ISSUE TITLE
Issue with OneNote Online

### ISSUE THREAD

**Issue by sirber** [xybu/onedrive-d-old#147]
Hi,

The last time (~6 months ago) I tried onedrive-d, it broke my OneNone Online documents (and I lost the data). Is it still the case?

**Comment by filicado** [comment]
Dear sirber, can you be a bit more specific?

There are OneNote Online notebooks (linked to and manageable via OneNote Online) and then there are simply OneNote notebooks that happen to be located in OneDrive.

In Windows 7 my OneNote Online notebooks (the first kind as described above) aren't actually downloaded to the OneDrive folder by the Win7 sync desktop client. In the documents folder there is just an internet shortcut referring to online notebook. When I try to delete the shortcut it says that the link can't be removed. Most of my notebooks are synced as the second type described above. i.e. the whole folder in OneDrive (Of course this makes them unusable in Linux because there is no OneNote desktop client to open them and they are invisible to OneNote Online)

So what sort of OneNote data did you loose and how did it happen? Did you check whether the shortcuts still point to the notebooks?

**Comment by sirber** [comment]
Hi,

I lost the link to the OneNote Online notebook, and lost the notebook itself.
On windows 7 you cannot remove this special link, like you said.
I haven't finished a full sync yet (ubuntu installed on an usb hdd). I made a backup of my onenote, I'll post the results later this week!

Ragards,

Stéphane

Date: Thu, 2 Apr 2015 08:57:13 -0700

**Comment by xybu** [comment]
OneNote link files should have crashed onedrive-d < 1.0, and are always ignored for onedrive-d >= 1.0.

**Comment by sirber** [comment]
Hi, everything seems fine. Thank you!
