### ISSUE TITLE
GUI app not working (?) on lubuntu 14.04

### ISSUE THREAD

**Issue by coditoter** [xybu/onedrive-d-old#55]
Hello!
So quickly - I can install, login, choose my folder to sync but ... the app is not working. Nothing is uploading/downloading and the icon doesn't appear on tray. The folder name is simple - onedrive .It's inside my home folder.

Reinstallation log:
http://pastebin.com/zAdREnvb
Starting demon log:
http://pastebin.com/hLAejdZQ

And 1 more thing about onedrive-d working in console. onedrive-cli tree shows the tree. I can upload files using onedrive-cli put too. However, it's impossible to upload folders.
Waiting 4 reply.

**Comment by xybu** [comment]
system cannot register notification handler on dbus... Looks like the components I chose have compatibility issue with lxde...

Sincerely,
Xiangyu Bu

**Comment by coditoter** [comment]
But it it possible to change/repair? 
I think that the problem isn't connected with Openbox - I have Crunchbang and there everything works.

**Comment by that-damn-cat** [comment]
I get this same issue, but I have this installed with the community AUR package in Arch. https://aur.archlinux.org/packages/onedrive-d-git/

**Comment by xybu** [comment]
Thanks again for reporting the issue. The GUI lib, pygtk, is a wrong choice and was last updated in Nov 2011 if I remember correctly. It is also a wrong decision to embed the daemon inside the GUI.

A workaround for this issue is to edit ~/.onedrive/user.conf manually and add/change the rootPath key to the dir you want to sync with OneDrive.

Unfortunately still with some urgent work at hand (didn't take a break during summer at all...) I don't have enough time to dive into the problem or change the GUI lib, and...

actually I am spending most of my free time on branch 1.0.0-dev. The code is rewritten with my own API library, new architecture, and Py3k. Many historical problems have been solved or made easy to solve. The new GUI lib, pygi, is way better and if it doesn't work on non-gnome environments, I can simply write a new observer component with PyQt which should cover the whole of non-gnome world. And the GUI component is totally optional if you prefer the command-line interface... Umm I shouldn't brag here just in case... But please have a look :)

**Comment by xybu** [comment]
Felt bad that the experimental versions brought so much trouble to you and others. Hopefully I can bring a production-level version in 1.0.0 and you guys are still interested in helping test it.

**Comment by DGPickett** [comment]
I just installed it on 14.04, a lot of file got uploaded, but now it seems stuck and many files/dirs not in sync are listed as 'untouched' in the daemon output.  I killed and restarted, but no additional uploads happen.

.
.
.
/home/dgp/Pictures/_myPix/SSPX0697.jpg is an untouched file.
/home/dgp/Pictures/_myPix/SSPX0722.jpg is an untouched file.
Thread-70: done.
Thread-71: The following items are untouched yet:
['04', '05', '03']
/home/dgp/Pictures/2014/04 is an untouched dir.
/home/dgp/Pictures/2014/05 is an untouched dir.
/home/dgp/Pictures/2014/03 is an untouched dir.
Thread-71: done.

**Comment by coditoter** [comment]
@xybu92 
Will it be possible to delete files automatically in the new version? And I think that (if you could) it'd be great to get rid of the annoying notifications of every file. If you upload a big file - OK, but I code in C++ wxWidgets and the notifications cover sometimes my code ;).
And (again) it'd be a nice thing to have "share" option in GUI. And that's the end of my suggestions ;) .

**Comment by coditoter** [comment]
And BTW - wxWidgets's also python implementation if you are interested in it. And what's more, it uses native-GUI things (Qt only imitates).

**Comment by xybu** [comment]
With a sqlite database that stores the last "snapshot" of OneDrive repo there is a lot more than we can do and the program will go more intelligent.

And again with GUI as an observer and sqlite db to store all pending notifications the messages can finally be grouped and there will be much less messages (and you can even turn it off to get rid of it).

Not familiar with wx but a similar observer should be easily written. The daemon works without the GUI by default and hooks UI given by command-line args.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by that-damn-cat** [comment]
A workaround for this issue is to edit ~/.onedrive/user.conf manually and add/change the rootPath key to the dir you want to sync with OneDrive.

This file does not yet exist for me. Is there a skeleton file for this where I can put in the rootPath key or how should this file be structured?
